### ISSUE TITLE
Expired cert.

### ISSUE THREAD

**Issue by ryneeverett** [b1nary/OSI-Model#1]
Looks like the ssl certificate is expired.

I was going to suggest [hosting on github pages](http://nanoc.ws/doc/deploying/#with-github-pages-or-bitbucket) but I guess it [doesn't have ssl for custom domains yet](https://github.com/isaacs/github/issues/156) anyway.

**Comment by b1nary** [comment]
fixed it but forgot to close it. 

I may change to Github hosting at some point, for now its part of my other infrastructure with (now) auto updating certs :)

**Comment by b1nary** [comment]
fixed it but forgot to close it. 

I may change to Github hosting at some point, for now its part of my other infrastructure with (now) auto updating certs :)
